@startuml

title __SERVICE's Class Diagram__\n

  package  {
    package site.namsu.sweng {
      package site.namsu.sweng.core.service {
        class ChatService {
        }
      }
    }
  }
  

  package  {
    package site.namsu.sweng {
      package site.namsu.sweng.core.service {
        class CheckService {
            - dao : Dao<User>
            + isSignedOrNull()
            + isAdmin()
            + isCorrectEmail()
        }
      }
    }
  }
  

  package  {
    package site.namsu.sweng {
      package site.namsu.sweng.core.service {
        class EncodeService {
            + encodePassword()
            - SHA256()
        }
      }
    }
  }
  

  package  {
    package site.namsu.sweng {
      package site.namsu.sweng.core.service {
        class LoadService {
            + load()
            + loadAll()
        }
      }
    }
  }
  

  package  {
    package site.namsu.sweng {
      package site.namsu.sweng.core.service {
        class MailService {
            + sendContactMailSuccessful()
            + sendResetMailSuccessful()
            {static} - send()
        }
      }
    }
  }
  

  package  {
    package site.namsu.sweng {
      package site.namsu.sweng.core.service {
        class ResetService {
            + resetPassword()
            + resetEmail()
        }
      }
    }
  }
  

  package  {
    package site.namsu.sweng {
      package site.namsu.sweng.core.service {
        class SessionService {
            - session : HttpSession
            + store()
            + read()
            + remove()
            + invalidate()
            + SessionService()
        }
      }
    }
  }
  

  package  {
    package site.namsu.sweng {
      package site.namsu.sweng.core.service {
        class StoreService {
            + storeSuccessful()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
